# Generated by Django 5.2.7 on 2025-10-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='IngredientModel',
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipeModel',
        ),
        migrations.RenameModel(
            old_name='Unit',
            new_name='UnitModel',
        ),
    ]
