# Generated by Django 5.2.7 on 2025-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredient_ingredientmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='type',
            field=models.TextField(default='Acompañamiento', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
