# Generated by Django 4.2.26 on 2025-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='type',
        ),
    ]
