# Generated by Django 4.2.26 on 2025-11-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipetypemodel_remove_recipemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipetypemodel'),
            preserve_default=False,
        ),
    ]
